version: "3"
services:
  client:
    env_file: .env
    build:
      context: .
      dockerfile: ./client/Dockerfile
    image: gyataro/cryptpaste-client
    volumes:
      - ./client:/cryptpaste/client:rw
      - /cryptpaste/client/node_modules
    ports:
      - "${CLIENT_PORT}:8080"
      - "35729:35729"

  server:
    env_file: .env
    build:
      context: .
      dockerfile: ./server/Dockerfile
    image: gyataro/cryptpaste-server
    volumes:
      - ./server:/cryptpaste/server:ro
      - /cryptpaste/server/node_modules
    ports:
      - "${SERVER_PORT}:3000"
    depends_on:
      - mongo
    
  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  
volumes:
  mongodb: