version: "3"
services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    image: gyataro/cryptpaste-server
    volumes:
      - ./server:/cryptpaste/server:ro
      - /cryptpaste/server/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    
  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  
volumes:
  mongodb: